"""
Per-language-family calibration constants.

Generated by scripts/calibrate.py from the Translation Fidelity Atlas benchmark
(540 experimental cells across 45 languages, 8 families, 6 domains, 2 translators).

Maps cross-lingual embedding similarity -> expected BLEU quality (0-100) via a
linear fit per language family. Family granularity chosen because language family
explains ~3.3x more quality variance than content domain in the source research.

DO NOT EDIT BY HAND. Re-run scripts/calibrate.py to regenerate.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CalibrationCurve:
    """Linear calibration: expected_bleu = slope * embedding_similarity + intercept."""

    slope: float
    intercept: float
    rmse: float
    correlation: float
    n_samples: int
    embedding_min: float
    embedding_max: float


FAMILY_CALIBRATION: dict[str, CalibrationCurve] = {
    "east_asian": CalibrationCurve(
        slope=116.3179,
        intercept=-56.8065,
        rmse=7.12,
        correlation=0.784,
        n_samples=36,
        embedding_min=0.6565,
        embedding_max=0.9696,
    ),
    "germanic": CalibrationCurve(
        slope=195.6177,
        intercept=-113.1871,
        rmse=7.14,
        correlation=0.871,
        n_samples=84,
        embedding_min=0.6404,
        embedding_max=0.9851,
    ),
    "romance": CalibrationCurve(
        slope=164.5286,
        intercept=-84.7999,
        rmse=6.56,
        correlation=0.763,
        n_samples=84,
        embedding_min=0.7923,
        embedding_max=0.9838,
    ),
    "semitic": CalibrationCurve(
        slope=187.3391,
        intercept=-105.0367,
        rmse=6.95,
        correlation=0.891,
        n_samples=36,
        embedding_min=0.7262,
        embedding_max=0.984,
    ),
    "slavic": CalibrationCurve(
        slope=178.7709,
        intercept=-103.6859,
        rmse=8.12,
        correlation=0.797,
        n_samples=108,
        embedding_min=0.7237,
        embedding_max=0.9694,
    ),
    "south_se_asian": CalibrationCurve(
        slope=161.6728,
        intercept=-88.2112,
        rmse=7.86,
        correlation=0.79,
        n_samples=108,
        embedding_min=0.7156,
        embedding_max=0.978,
    ),
    "turkic": CalibrationCurve(
        slope=156.1539,
        intercept=-84.6423,
        rmse=7.31,
        correlation=0.86,
        n_samples=48,
        embedding_min=0.6243,
        embedding_max=0.9622,
    ),
    "uralic": CalibrationCurve(
        slope=182.1998,
        intercept=-104.6765,
        rmse=7.67,
        correlation=0.856,
        n_samples=36,
        embedding_min=0.7296,
        embedding_max=0.9621,
    ),
}


LANG_TO_FAMILY: dict[str, str] = {
    "af": "germanic",
    "ar": "semitic",
    "az": "turkic",
    "bg": "slavic",
    "bn": "south_se_asian",
    "ca": "romance",
    "cs": "slavic",
    "da": "germanic",
    "de": "germanic",
    "es": "romance",
    "et": "uralic",
    "fi": "uralic",
    "fr": "romance",
    "gl": "romance",
    "hi": "south_se_asian",
    "hr": "slavic",
    "hu": "uralic",
    "id": "south_se_asian",
    "is": "germanic",
    "it": "romance",
    "iw": "semitic",
    "ja": "east_asian",
    "kk": "turkic",
    "ko": "east_asian",
    "ms": "south_se_asian",
    "mt": "semitic",
    "nl": "germanic",
    "no": "germanic",
    "pl": "slavic",
    "pt": "romance",
    "ro": "romance",
    "ru": "slavic",
    "sk": "slavic",
    "sl": "slavic",
    "sr": "slavic",
    "sv": "germanic",
    "ta": "south_se_asian",
    "te": "south_se_asian",
    "th": "south_se_asian",
    "tr": "turkic",
    "uk": "slavic",
    "ur": "south_se_asian",
    "uz": "turkic",
    "vi": "south_se_asian",
    "zh": "east_asian",
    "zh-cn": "east_asian",
}


def get_family(language: str) -> str | None:
    """Return language family for an ISO code, or None if unknown."""
    return LANG_TO_FAMILY.get(language.lower())
