"""
Fit per-language-family calibration curves from the benchmark CSV.

Reads data/combined_long.csv and regenerates
src/translation_fidelity/calibration_data.py.

Run from repo root:  uv run python scripts/calibrate.py

This is a DEV-TIME script. End users never run it — the package ships the
generated constants in calibration_data.py.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = REPO_ROOT / "data" / "combined_long.csv"
OUTPUT_PATH = REPO_ROOT / "src" / "translation_fidelity" / "calibration_data.py"


def fit_family_curves(df: pd.DataFrame) -> dict[str, dict]:
    """Fit linear embedding->bleu curve per family."""
    curves: dict[str, dict] = {}
    for family in sorted(df["family"].unique()):
        sub = df[df["family"] == family]
        x, y = sub["embedding"].to_numpy(), sub["bleu"].to_numpy()
        slope, intercept = np.polyfit(x, y, 1)
        rmse = float(np.sqrt(((y - (slope * x + intercept)) ** 2).mean()))
        curves[family] = {
            "slope": round(float(slope), 4),
            "intercept": round(float(intercept), 4),
            "rmse": round(rmse, 2),
            "correlation": round(float(sub["embedding"].corr(sub["bleu"])), 3),
            "n_samples": int(len(sub)),
            "embedding_min": round(float(x.min()), 4),
            "embedding_max": round(float(x.max()), 4),
        }
    return curves


def build_lang_to_family(df: pd.DataFrame) -> dict[str, str]:
    """Map each language code to its family."""
    mapping = df.groupby("language")["family"].first().to_dict()
    # normalise keys to lowercase, add zh alias
    out = {k.lower(): v for k, v in mapping.items()}
    if "zh-cn" in out:
        out["zh"] = out["zh-cn"]
    return dict(sorted(out.items()))


def render_module(curves: dict[str, dict], lang_map: dict[str, str]) -> str:
    """Render the calibration_data.py source file."""
    lines = [
        '"""',
        "Per-language-family calibration constants.",
        "",
        "Generated by scripts/calibrate.py from the Translation Fidelity Atlas benchmark",
        "(540 experimental cells across 45 languages, 8 families, 6 domains, 2 translators).",
        "",
        "Maps cross-lingual embedding similarity -> expected BLEU quality (0-100) via a",
        "linear fit per language family. Family granularity chosen because language family",
        "explains ~3.3x more quality variance than content domain in the source research.",
        "",
        "DO NOT EDIT BY HAND. Re-run scripts/calibrate.py to regenerate.",
        '"""',
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "",
        "",
        "@dataclass(frozen=True)",
        "class CalibrationCurve:",
        '    """Linear calibration: expected_bleu = slope * embedding_similarity + intercept."""',
        "    slope: float",
        "    intercept: float",
        "    rmse: float",
        "    correlation: float",
        "    n_samples: int",
        "    embedding_min: float",
        "    embedding_max: float",
        "",
        "",
        "FAMILY_CALIBRATION: dict[str, CalibrationCurve] = {",
    ]
    for fam, c in curves.items():
        lines += [
            f'    "{fam}": CalibrationCurve(',
            f"        slope={c['slope']}, intercept={c['intercept']},",
            f"        rmse={c['rmse']}, correlation={c['correlation']},",
            f"        n_samples={c['n_samples']},",
            f"        embedding_min={c['embedding_min']}, embedding_max={c['embedding_max']},",
            "    ),",
        ]
    lines += ["}", "", ""]

    lines.append("LANG_TO_FAMILY: dict[str, str] = {")
    items = list(lang_map.items())
    for i in range(0, len(items), 4):
        chunk = items[i : i + 4]
        rendered = " ".join(f'"{k}": "{v}",' for k, v in chunk)
        lines.append(f"    {rendered}")
    lines += ["}", "", ""]

    lines += [
        "def get_family(language: str) -> str | None:",
        '    """Return language family for an ISO code, or None if unknown."""',
        "    return LANG_TO_FAMILY.get(language.lower())",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    if not CSV_PATH.exists():
        raise SystemExit(f"Benchmark CSV not found at {CSV_PATH}")

    df = pd.read_csv(CSV_PATH)
    print(
        f"Loaded {len(df)} rows, {df['language'].nunique()} languages, "
        f"{df['family'].nunique()} families"
    )

    curves = fit_family_curves(df)
    lang_map = build_lang_to_family(df)

    print("\nPer-family fit:")
    for fam, c in curves.items():
        print(
            f"  {fam:16s} slope={c['slope']:8.2f} rmse={c['rmse']:5.2f} "
            f"corr={c['correlation']:.3f} n={c['n_samples']}"
        )

    OUTPUT_PATH.write_text(render_module(curves, lang_map), encoding="utf-8")
    print(f"\nWrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
